ifeq ($(LIBRETRO_COMM_DIR),)
	LIBRETRO_COMM_DIR := $(CORE_DIR)/libretro-common
endif

INCFLAGS := -I$(LIBRETRO_COMM_DIR)/include

SOURCES_C := $(CORE_DIR)/libretro.c \
	$(CORE_DIR)/game_noncairo.c \
	$(CORE_DIR)/game_shared.c
