install-emsdk:
	cd `mktemp -d` && git clone https://github.com/emscripten-core/emsdk . && ./emsdk install latest && ./emsdk activate latest && bash -c "source emsdk_env.sh"

build-core:
	emmake make -f Makefile.libretro platform=emscripten
	git clone https://github.com/libretro/RetroArch.git && \
	cp 2048_libretro_emscripten.bc RetroArch/libretro_emscripten.bc
	cd RetroArch && emmake make -f Makefile.emscripten LIBRETRO=2028 -j all
