name: CI PS2

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build-platform:
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:latest
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        apk add build-base git bash
    
    - name: Get Information Variables
      id: core
      run: |
        echo "platform=$(echo ps2)" >> $GITHUB_OUTPUT
        echo "sha8=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_OUTPUT

    - name: Compile project
      run: |
        make -f Makefile.libretro platform=${{ steps.core.outputs.platform }} -j$(getconf _NPROCESSORS_ONLN)

    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v3
      with:
        name: 20408_libretro_${{ steps.core.outputs.platform }}-${{ steps.core.outputs.sha8 }}
        path: 2048_libretro_${{ steps.core.outputs.platform }}.a
